### ISSUE TITLE
Tracking players stats?

### ISSUE THREAD

**Issue by olejsc** [stfwn/savage-metaserver#35]
I've noticed [issue 19](https://github.com/stfwn/savage-metaserver/issues/19) about stats tracking, but it seems to focus on tracking match stats (which is super useful too!). 

Will the metaserver support player stats ? Is it something you would accept PR's for, tweaking the database to support it on a per-user basis? 

- Madmod :-)

**Comment by biggeruniverse** [comment]
My personal vision on that is match stats _include_ player stats, taken at intervals throughout the match. I envisioned a system where a validated server requests a "new match" from the auth system sending some pertinent info like map etc, Then auth tells it a "match id" that it then uses to send player stats snapshots over the course of the match. This may be a little much, so we might end up keeping this info until the end of the match, aggregating it, and then sending the aggregates to the auth server.

**Comment by stfwn** [comment]
I agree with the above, #19 proposes having a `MatchUpdate` object that (verified) servers can send to the metaserver whenever they want. The player ids and their stats within the match should be in there. When you're running analysis, you take the match updates you're interested in and compute the player stats from it.

This way we only store the most raw form of the data, and everything else can be derived from that. This enables more granular insights than before, e.g. how many buffs did player X take on average in the first Y min of matches on map Z?
